import { createHash } from 'node:crypto';
import { readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { defineConfig, type Plugin } from 'vite';

/**
 * Generates `sw.js` at build time (docs/MOBILE.md §7): it precaches the app shell (index.html,
 * the hashed JS / CSS / worker chunks and the public files) so the app starts fast and solo
 * plays offline. The cache name is a hash of the file list, so every deploy installs a new
 * worker, which waits until the page asks it to take over ("Update available — tap to reload").
 * It only serves same-origin GET requests; the game server's WebSocket never goes through it.
 */
function serviceWorker(): Plugin {
  let publicDir = '';
  return {
    name: 'tdt-service-worker',
    apply: 'build',
    configResolved(config) {
      publicDir = config.publicDir;
    },
    generateBundle(_options, bundle) {
      const publicFiles = listFiles(publicDir).map((f) => `/${f}`);
      const built = Object.keys(bundle)
        .filter((f) => !f.endsWith('.map') && f !== 'index.html' && f !== 'sw.js')
        .map((f) => `/${f}`);
      const files = ['/index.html', ...built, ...publicFiles.filter((f) => f !== '/sw.js')].sort();
      const version = createHash('sha256').update(files.join('\n')).digest('hex').slice(0, 12);
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: swSource(version, files) });
    },
  };
}

function listFiles(dir: string): string[] {
  const out: string[] = [];
  const walk = (d: string) => {
    for (const name of readdirSync(d)) {
      const p = join(d, name);
      if (statSync(p).isDirectory()) walk(p);
      else out.push(relative(dir, p).split('\\').join('/'));
    }
  };
  try {
    walk(dir);
  } catch {
    // No public directory.
  }
  return out;
}

function swSource(version: string, files: string[]): string {
  return `// Generated by vite.config.ts at build time. Do not edit.
const CACHE = 'tdt-${version}';
const SHELL = ${JSON.stringify(files)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(SHELL)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('tdt-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// The page asks a waiting worker to take over when the player taps "Update available".
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Only this site's own files; never the game server.
  if (url.origin !== self.location.origin || url.pathname === '/sw.js') return;
  if (req.mode === 'navigate') {
    // App shell first (fast start, offline solo); the network if it is not cached yet.
    event.respondWith(caches.match('/index.html').then((hit) => hit || fetch(req)));
    return;
  }
  event.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req)));
});
`;
}

export default defineConfig({
  plugins: [serviceWorker()],
  worker: { format: 'es' },
  build: {
    target: 'es2022',
    // PixiJS is large; keep it in its own chunk.
    chunkSizeWarningLimit: 1200,
  },
});
