/**
 * Structured status for the `/?progress` page.
 *
 * TASKS.md is the human tracker and stays the authority. This file is what the
 * dashboard reads. When a pull request finishes a task, update both TASKS.md and
 * this file in that same PR. How: docs/PROGRESS.md. Do not add a third list.
 *
 * Seeded from main as of 2 Oct 2026. Production protocol is 16.
 * Gate 1 passed 2 Oct 2026 (Android, PC, iPhone Safari friends). This page only reports status.
 */

import type { ProgressData, ProgressItem, ProgressProof, ProgressSection } from './model';

const REPO = 'https://github.com/Han1989/tgt-td-cld';

function pr(n: number): ProgressProof {
  return { label: `PR #${n}`, href: `${REPO}/pull/${n}` };
}

const sections: ProgressSection[] = [
  {
    id: 'gate1',
    title: 'Gate 1 · Friends playtest',
    blurb: 'Passed 2 Oct 2026. Friends played on Android, PC, and iPhone Safari, so Phase 6 may proceed.',
    group: 'archive',
  },
  {
    id: 'playtest2',
    title: 'Playtest 2 · work orders',
    blurb: 'Follow-up from the 2 Oct 2026 friends session. P2-01 to P2-04b are done (PR #57, #63, #66, #70, #73). The retest (P2-05) is still open. Not the overnight auto-pull list.',
    group: 'now',
  },
  {
    id: 'han',
    title: 'Han, in parallel',
    blurb: 'Only Han can do these: phones, friends, accounts, and the hook-test server. Preview links (H-01) are done. The rest do not block the team from reading the tracker.',
    group: 'now',
  },
  {
    id: 'discovery',
    title: 'Discovery and rollout',
    blurb: 'Public soft-launch path. Measurement, the privacy notice (D-07), the link preview and the press kit are in. Posts (D-02–D-06) and the go/no-go are Han, and still open; the privacy email (H-07) comes first.',
    group: 'now',
  },
  {
    id: 'polish',
    title: 'Polish · T-00–T-06',
    blurb: 'The polish path is done. CI, Hard, pings, the tutorial, projectile art, the docs, and co-op hook signals.',
    group: 'archive',
  },
  {
    id: 'earlier',
    title: 'Shipped earlier',
    blurb: 'The checklist’s “Done · 12 of 50”, already on main. The hook-test branch stays unmerged.',
    group: 'archive',
  },
  {
    id: 'p6a',
    title: 'Phase 6a · Accounts and data',
    blurb: 'Unblocked 2 Oct 2026 (Gate 1 passed). Not started.',
    group: 'later',
  },
  {
    id: 'p6b',
    title: 'Phase 6b · Clans',
    blurb: 'Unblocked 2 Oct 2026 (Gate 1 passed). Not started.',
    group: 'later',
  },
  {
    id: 'p6c',
    title: 'Phase 6c · Loot and progression',
    blurb: 'Unblocked 2 Oct 2026 (Gate 1 passed). Combos are done (sim PR #66, presentation PR #83); the rest is not started. The hook-test branch is not merged.',
    group: 'later',
  },
  {
    id: 'p6d',
    title: 'Phase 6d · Competition',
    blurb: 'Unblocked 2 Oct 2026 (Gate 1 passed). Not started.',
    group: 'later',
  },
  {
    id: 'gate2',
    title: 'Gate 2 · Public soft launch',
    blurb: 'Public soft-launch path, still open, with the Reddit posts (D-02–D-06). Same measurement bar as D-01 and D-06. Han calls the gate.',
    group: 'later',
  },
  {
    id: 'p7',
    title: 'Phase 7 · Monetisation',
    blurb: 'After Gate 2. No prices or odds without Han.',
    group: 'later',
  },
  {
    id: 'p8',
    title: 'Phase 8 · Live PvP',
    blurb: 'Last, after the co-op live game.',
    group: 'later',
  },
  {
    id: 'p9',
    title: 'Phase 9 · Reach',
    blurb: 'Only after Discovery shows strangers stay. Store-facing build leads with 1p and 2p; 3p stays the community flagship.',
    group: 'later',
  },
  {
    id: 'backlog',
    title: 'Backlog',
    blurb: 'Not scheduled. More maps, and one open decision.',
    group: 'later',
  },
];

const items: ProgressItem[] = [
  {
    id: 'g1-render',
    title: 'Render on Starter for the evening',
    owner: 'Han',
    status: 'done',
    section: 'gate1',
    note: 'Passed 2 Oct 2026 with Gate 1. Friends played on Android, PC, and iPhone Safari.',
    proof: { label: 'Passed 2 Oct 2026', href: `${REPO}/blob/main/TASKS.md` },
  },
  {
    id: 'g1-play',
    title: 'Play 2–3 matches with two friends',
    owner: 'Han',
    status: 'done',
    section: 'gate1',
    note: 'Passed 2 Oct 2026. Friends played on Android, PC, and iPhone Safari.',
    proof: { label: 'Passed 2 Oct 2026', href: `${REPO}/blob/main/TASKS.md` },
  },
  {
    id: 'g1-watch',
    title: 'Watch, don’t coach',
    owner: 'Han',
    status: 'done',
    section: 'gate1',
    note: 'Passed 2 Oct 2026 with the friends session on Android, PC, and iPhone Safari.',
    proof: { label: 'Passed 2 Oct 2026', href: `${REPO}/blob/main/TASKS.md` },
  },
  {
    id: 'g1-tune',
    title: 'Per-hero tuning from the match reports',
    owner: 'Team',
    status: 'done',
    section: 'gate1',
    note: 'Passed 2 Oct 2026 with Gate 1. Kit rework and sim balance from the session is Playtest 2 (P2-03).',
    proof: { label: 'Passed 2 Oct 2026', href: `${REPO}/blob/main/TASKS.md` },
  },
  {
    id: 'g1-gate',
    title: 'Gate: they ask to play again',
    owner: 'Han',
    status: 'done',
    section: 'gate1',
    note: 'Passed 2 Oct 2026. Friends on Android, PC, and iPhone Safari. Phase 6 may proceed.',
    proof: { label: 'Passed 2 Oct 2026', href: `${REPO}/blob/main/TASKS.md` },
  },
  {
    id: 'P2-01',
    title: 'Touch controls',
    owner: 'Team',
    status: 'done',
    section: 'playtest2',
    note: 'Client polish. Touch controls and phone UX, from the 2 Oct 2026 friends session.',
    proof: pr(57),
  },
  {
    id: 'P2-01b',
    title: 'Phone build and upgrade fix',
    owner: 'Both',
    status: 'in_progress',
    section: 'playtest2',
    note: 'Client. Han’s request in #57 was misread: one tap in the build ring builds (no “tap again”), a hold previews the range and stats without building, and the gold ↑ tags on towers are gone (tap the tower, then Upgrade). Han tests the preview on his phone before merging.',
    proof: pr(82),
  },
  {
    id: 'P2-02',
    title: 'Air waves and unspent gold',
    owner: 'Team',
    status: 'done',
    section: 'playtest2',
    note: 'Client polish. Teach air waves and unspent gold: flyer readability, anti-air teaching, and a gold nudge.',
    proof: pr(63),
  },
  {
    id: 'P2-03',
    title: 'Kit rework and sim balance',
    owner: 'Both',
    status: 'done',
    section: 'playtest2',
    note: 'Sim work (Claude). Kit rework and balance by simulation, merged as 05a3fc0 after Han’s review. The same work as SL-05.',
    proof: pr(66),
  },
  {
    id: 'P2-04',
    title: 'Ultimate presentation and combo cue',
    owner: 'Team',
    status: 'done',
    section: 'playtest2',
    note: 'Client. Each combo (Meteor Rain, Stun Storm, Shockwave) has its own ribbon, colour and strikes, and a finished rain or combo shows how many creeps it killed. No aim circles.',
    proof: { label: 'PR #70', href: `${REPO}/pull/70` },
  },
  {
    id: 'P2-04b',
    title: 'Cast-together prompt, ultimate shake and heal feedback',
    owner: 'Team',
    status: 'done',
    section: 'playtest2',
    note: 'Client. The part of Task 4 that PR #70 left out: a flare, blink, kick and sound on every cast, one exact kill count per ultimate, the R pulse and Combo! ring, a Screen shake setting (Off, Normal, Strong), Iron Vow heal on every hero and teammate chip, and kills per ultimate and combos per pair on the end screen (protocol 18). The P2-05 retest waited for it. Built by Claude Code.',
    proof: pr(73),
  },
  {
    id: 'P2-04c',
    title: 'Meteors you can see falling',
    owner: 'Team',
    status: 'todo',
    section: 'playtest2',
    note: 'Client. Meteor, Meteor Rain and Shockwave drop visible meteors about half a second before each pulse onto the creeps it will strike, over a red warning circle, with a red wash and sky meteors at the cast, a bigger finale and a falling whistle. Same kills and timing. Waiting on Han trying the preview on his phone. Built by Claude Code.',
  },
  {
    id: 'P2-05',
    title: 'Retest',
    owner: 'Han',
    status: 'todo',
    section: 'playtest2',
    note: 'Han retests after Playtest 2 tasks P2-01 through P2-04b.',
  },
  {
    id: 'P2-06',
    title: 'Tower repair',
    owner: 'Both',
    status: 'done',
    section: 'playtest2',
    note: 'Sim and client, protocol 19. Instant repair for 0.3 of the gold spent times the share of HP missing. Phone ring button, desktop panel and F, and a one-time hint. Reports carry repairs, repair gold and towers destroyed per player for Playtest 3; balance is provisional until then. Merged. Built by Claude Code.',
    proof: pr(90),
  },
  {
    id: 'P2-07',
    title: 'Floating stick and taps that register',
    owner: 'Both',
    status: 'done',
    section: 'playtest2',
    note: 'Client only. Friends found the joystick too small and hit skills by accident. Drag anywhere on the map to walk: the stick appears under the thumb and follows it. Round 2, after Han tried PR #92 one-thumbed: the skills are back in the one-thumb arc around the stick, at least 24 px apart and 24 px from the stick, with no Skills button (hold any skill to read them all). Settings has two rows, Stick (Floating, Fixed) and Skills (Around the stick, Right corner, Left corner). A drag never taps a skill or selects; two fingers steer and cast at once. Tap or hold is decided from the timestamps of the touch events, so a stalled frame no longer turns a quick tap into a hold. Built by Claude Code. Round 3, after Han tested round 2 on his phone (sim and client, protocol stays 19): a point skill is cast at once when a move, stop or attack follows it in the same tick, so Q and W fire while you steer; the left corner reads Q, W, R like the right. A second point cast in the same tick still replaces the first, left for the rebalance after Playtest 3. Merged (PRs #93 and #94).',
    proof: pr(94),
  },
  {
    id: 'P2-08',
    title: 'Start-up watchdog',
    owner: 'Team',
    status: 'done',
    section: 'playtest2',
    note: 'Client only, protocol stays 19. Browser-test runs sat on Loading for 150 s twice. After 15 s on screen without the first screen the splash says it is still loading and offers Reload, and keeps waiting; no WebGL, or a context lost while starting, says so at once. Each is reported once as a crash report with a fixed reason (boot_timeout, webgl_unavailable, webgl_context_lost). Two Pixi 8.21 start-up hangs closed: a lost context froze the page in a loop no timer can reach, and no WebGL waited on a WebGPU request with no timeout. Auto-merge. Built by Claude Code.',
    proof: pr(95),
  },
  {
    id: 'H-01',
    title: 'Let friends open preview links',
    owner: 'Han',
    status: 'done',
    section: 'han',
    note: 'Vercel Deployment Protection → Vercel Authentication is Disabled on the tgt-td-cld project. Han confirmed 1 Oct 2026. Friends opening a preview do not see a Vercel login page.',
    proof: { label: 'Han, 1 Oct 2026', href: `${REPO}/blob/main/docs/GAME_DESIGN.md` },
  },
  {
    id: 'H-02',
    title: 'Confirm the hook-test server',
    owner: 'Han',
    status: 'todo',
    section: 'han',
    note: 'In Render, check tgt-td-spike is Live and copy its address. /health should show shard H. On 30 Sep the public URL returned 404.',
  },
  {
    id: 'H-03',
    title: 'Try the hook test on a phone',
    owner: 'Han',
    status: 'todo',
    section: 'han',
    note: 'Solo practice is on main: ?practice=meteor-rain, then Practice Meteor Rain. The spike URL is retired. Then one online match with a friend on the production server.',
  },
  {
    id: 'H-04',
    title: 'Three music tracks (optional)',
    owner: 'Han',
    status: 'done',
    section: 'han',
    note: 'Done 1 Oct 2026. lobby.mp3, match.mp3, and boss.mp3 are in public/music (AI-generated via Google Gemini, by Han).',
    proof: pr(42),
  },
  {
    id: 'H-05',
    title: 'Test on an iPhone',
    owner: 'Han',
    status: 'todo',
    section: 'han',
    note: 'Safari has the most quirks. Run docs/MOBILE_TESTING.md once and fill in its Results table.',
  },
  {
    id: 'H-06',
    title: 'Give the team GitHub access',
    owner: 'Han',
    status: 'todo',
    section: 'han',
    note: 'Write access for branches and pull requests. Merging stays with Han.',
  },
  {
    id: 'H-07',
    title: 'Privacy contact email',
    owner: 'Han',
    status: 'todo',
    section: 'han',
    note: 'Before the Reddit posts: replace the marked placeholder on privacy.html with the address players write to for a copy or deletion of their play data (D-07). The server already prunes events.jsonl to 30 days (PR #75).',
  },
  {
    id: 'D-01',
    title: 'Channel analytics',
    owner: 'Team',
    status: 'done',
    section: 'discovery',
    note: 'Playtime, D1/D7 retention, repeat visits, and a post-match rating, tagged by source. First-party HTTP on the game server. Not Phase 6a accounts. D30 came with p6a-analytics (PR #85).',
    proof: pr(25),
  },
  {
    id: 'SL-01',
    title: 'Soft-launch co-op presentation',
    owner: 'Team',
    status: 'done',
    section: 'discovery',
    note: 'Mirrored ping and emote burst, gift sent/received toasts, and a twin-ultimate ribbon from cast events. Sim signals (leak lane, gift totals, syncCast, boss hints) are protocol 14 (T-06). The live wires are SL-02.',
    proof: pr(35),
  },
  {
    id: 'SL-02',
    title: 'Soft-launch HUD hooks',
    owner: 'Team',
    status: 'done',
    section: 'discovery',
    note: 'Lane clutch names the leaking lane. The end screen shows gold given and received. The twin ribbon prefers syncCast. Boss waves add advisory lane banners. Protocol stays 14.',
    proof: pr(36),
  },
  {
    id: 'SL-03',
    title: 'Together-kill flash',
    owner: 'Team',
    status: 'done',
    section: 'discovery',
    note: 'Two or more living heroes who damaged the same creep within 2 seconds of the kill get a short flash in their seat colours, an edge glow, and a dual-pitch chime. No rewards. Protocol stays 14. Towers share damage.by, so a living player’s towers count until Gameplay adds a hero-only signal.',
    proof: pr(38),
  },
  {
    id: 'SL-04',
    title: 'Soft-launch hook on main',
    owner: 'Team',
    status: 'done',
    section: 'discovery',
    note: 'Protocol 16. Meteor Rain is the one combo: Arrow Storm and Meteor are lane rains, and a second cast within 2 seconds fuses them into a denser shared rain. Quick wave 10 Matriarch needs two lanes; Full wave 10 does not. Solo practice is ?practice=meteor-rain. Warden has Blood Hunger and Iron Vow. The stick overrides melee chase. Do not merge the spike branch.',
    proof: pr(45),
  },
  {
    id: 'SL-05',
    title: 'Kit rework and balance by simulation (Playtest 2)',
    owner: 'Team',
    status: 'done',
    section: 'discovery',
    note: 'Protocol 17. Arrow Storm and Meteor are instant lane rains again (no aiming, no caps) and much stronger, the Warden hits flyers and Iron Vow heals the team, three combos (Meteor Rain, Stun Storm, Shockwave) with no overlap check, no Hard finale deduction. Balanced with a novice bot and npm run balance:matrix. Merged after Han’s review.',
    proof: pr(66),
  },
  {
    id: 'D-07',
    title: 'Privacy notice before strangers play',
    owner: 'Team',
    status: 'done',
    section: 'discovery',
    note: 'Client only, no protocol change. A plain-language page at /privacy.html (what is collected and why, no accounts or third-party trackers, 30 days, deletion by email), linked from the lobby, the rating control and Settings; the note box asks for no personal details; Settings → Play data turns analytics off for this browser (off by default with Global Privacy Control or Do Not Track). The email is H-07.',
    proof: pr(74),
  },
  {
    id: 'D-08',
    title: 'Link preview and first load',
    owner: 'Team',
    status: 'done',
    section: 'discovery',
    note: 'Client only, protocol stays 18. A shared link shows a card drawn from the game’s own art and README’s pitch; tagged links keep the card and their ?src=. A boot splash, Play solo one tap with no scrolling on phones, first load measured on a throttled Pixel 7. Press kit: docs/PRESS.md.',
    proof: pr(77),
  },
  {
    id: 'D-02',
    title: 'Post to r/PlayMyGame',
    owner: 'Han',
    status: 'todo',
    section: 'discovery',
    note: 'Follow the sub’s rules. One clear link, with the channel tag.',
  },
  {
    id: 'D-03',
    title: 'Post to r/incremental_games',
    owner: 'Han',
    status: 'todo',
    section: 'discovery',
    note: 'Only if the pitch fits. Follow the sub’s rules and use the channel tag.',
  },
  {
    id: 'D-04',
    title: 'Post to r/cozygames',
    owner: 'Han',
    status: 'todo',
    section: 'discovery',
    note: 'Only if the pitch fits. Follow the sub’s rules and use the channel tag.',
  },
  {
    id: 'D-05',
    title: 'CrazyGames Basic Launch',
    owner: 'Han',
    status: 'todo',
    section: 'discovery',
    note: 'Same work as Gate 2 g2-launch. Before or alongside store submission, not instead of polish.',
  },
  {
    id: 'D-06',
    title: 'Review channels and call go or no-go',
    owner: 'Han',
    status: 'todo',
    section: 'discovery',
    note: 'Playtime, retention, and repeats per channel. Friends-only signal is not enough to push stores.',
  },
  {
    id: 'T-00',
    title: 'CI and branch protection',
    owner: 'Both',
    status: 'done',
    section: 'polish',
    note: 'GitHub Actions runs tests and the build on pull requests and main. main requires the ci check. Branch protection is on.',
    proof: pr(24),
  },
  {
    id: 'T-01',
    title: 'Hard difficulty and an expert bot',
    owner: 'Team',
    status: 'done',
    section: 'polish',
    note: 'Hard scales creep HP and counts. The casual bot stays the Normal 40–80 gate. The expert bot holds Hard at 40–80. Protocol 12.',
    proof: pr(28),
  },
  {
    id: 'T-02',
    title: 'Team pings and quick-chat',
    owner: 'Team',
    status: 'done',
    section: 'polish',
    note: 'Long-press or Alt-click pings the map. Six emotes, no free-text chat. Protocol 13.',
    proof: pr(29),
  },
  {
    id: 'T-03',
    title: 'First-match tutorial',
    owner: 'Team',
    status: 'done',
    section: 'polish',
    note: 'A new player’s first solo match is a skippable Quick lesson on Normal. Online rooms do not start it. Replay from Settings.',
    proof: pr(30),
  },
  {
    id: 'T-04',
    title: 'Projectile and trap art',
    owner: 'Team',
    status: 'done',
    section: 'polish',
    note: 'Every shot style and the Snare Trap are Runelight sprites. ?showcase lists them in Normal and Bright.',
    proof: pr(26),
  },
  {
    id: 'T-05',
    title: 'Docs clean-up',
    owner: 'Team',
    status: 'done',
    section: 'polish',
    note: 'README status, docs/ROADMAP.md, GAME_DESIGN §11, and AGENTS.md. Gate 1 passed 2 Oct 2026, so Phase 6 may proceed.',
    proof: pr(31),
  },
  {
    id: 'T-06',
    title: 'Soft-launch co-op hook signals',
    owner: 'Team',
    status: 'done',
    section: 'polish',
    note: 'Protocol 14. Leak events carry a lane. Reports count gold gifted and received. A syncCast marks overlapping ultimates, with no extra damage. Boss lane lines are advisory. Double-ping FX stays on the client.',
    proof: pr(34),
  },
  {
    id: 'a-units',
    title: 'Units art',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Heroes, creeps, and bosses drawn in Runelight.',
    proof: pr(16),
  },
  {
    id: 'a-branches',
    title: 'Old branches cleaned up',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Merged branches now delete themselves. A repository setting, not a pull request.',
  },
  {
    id: 'a-mana',
    title: 'Ultimates cost no mana',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Ultimates are cooldown only. Mana regen grows with level.',
    proof: { label: 'Decision log', href: `${REPO}/blob/main/docs/GAME_DESIGN.md` },
  },
  {
    id: 'a-mana-merge',
    title: 'Hero mana rework merged',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Free ultimates, level-scaled regen, and mana costs on the skill buttons.',
    proof: pr(17),
  },
  {
    id: 'a-cap3',
    title: 'Matches locked to 3 players',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'One player per lane. The 4-player setup is gone.',
    proof: pr(18),
  },
  {
    id: 'a-feel',
    title: 'Mobile feel pass',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Your hero draws its walk at once, solo renders 40 ms behind, and the Warden’s swing reads on a phone.',
    proof: pr(19),
  },
  {
    id: 'a-reach',
    title: 'Melee reach fix',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'A hero reaches a creep from attack range plus both radii. An idle melee hero steps in and fights.',
    proof: pr(20),
  },
  {
    id: 'a-fix1',
    title: 'Playtest round 1 fixes',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Match reports and replays, the team difficulty curve, and mana that lasts about twice as long.',
    proof: pr(21),
  },
  {
    id: 'a-sound',
    title: 'Sound pass',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Music and effects made in code with the Web Audio API. No sound files.',
    proof: pr(22),
  },
  {
    id: 'a-theme',
    title: 'Sound theme',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Japanese garden in the lobby, Three Kingdoms battles in a match. No recorded files yet.',
    proof: pr(23),
  },
  {
    id: 'b-spike',
    title: 'Hook test (never merge)',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Combo ultimates, a boss shield, and a solo bot ally, behind ?spike=hook. The branch stays unmerged. Meteor Rain, the wave-10 shield and solo practice shipped on main as SL-04.',
    proof: { label: 'Branch (do not merge)', href: `${REPO}/tree/claude/loving-hawking-7fvsu7` },
  },
  {
    id: 'p6a-db',
    title: 'Choose the database host',
    owner: 'Han',
    status: 'todo',
    section: 'p6a',
    note: 'Render Postgres, or AWS. Han decides.',
  },
  {
    id: 'p6a-accounts',
    title: 'Accounts and saved progress',
    owner: 'Team',
    status: 'todo',
    section: 'p6a',
    note: 'Play as a guest first. Link Google, Apple, or email later. Currencies and inventory live on the server.',
  },
  {
    id: 'p6a-analytics',
    title: 'Analytics and crash reports',
    owner: 'Team',
    status: 'done',
    section: 'p6a',
    note: 'Day-1, day-7 and day-30 return rates per channel (D30 survives the 30-day prune), where new players stop in their first visit, match results by mode, team, hero and channel, and crash reports, on the game server dashboard. Behind the Play data switch. No new service.',
    proof: pr(85),
  },
  {
    id: 'p6a-privacy',
    title: 'Privacy basics',
    owner: 'Team',
    status: 'done',
    section: 'p6a',
    note: 'Done for play without accounts: Download / Delete my data in Settings and on the privacy page, by a secret key only this browser holds; a one-time neutral age question before any play data (under 13 nothing is sent, 13 to 15 starts off); GDPR and PDPA rights in plain words. No database or new service. Account data joins it with p6a-accounts.',
    proof: pr(86),
  },
  {
    id: 'p6b-clans',
    title: 'Clans of 3',
    owner: 'Team',
    status: 'todo',
    section: 'p6b',
    note: 'Create, invite by link, join, and leave. Clan level and banner.',
  },
  {
    id: 'p6b-party',
    title: 'Play as a clan',
    owner: 'Team',
    status: 'todo',
    section: 'p6b',
    note: 'Party up and queue together. Quick-chat only.',
  },
  {
    id: 'p6c-combos',
    title: 'Combo ultimates',
    owner: 'Team',
    status: 'done',
    section: 'p6c',
    note: 'A fused effect for every hero pair: Meteor Rain, Stun Storm and Shockwave are in the sim (SL-05, PR #66). Stun Storm and Shockwave now have their own ribbon, sky, strikes, fuse burst and kill count, like Meteor Rain (client only). Do not merge claude/loving-hawking-7fvsu7.',
    proof: { label: 'PR #83', href: `${REPO}/pull/83` },
  },
  {
    id: 'p6c-raids',
    title: 'Raid bosses',
    owner: 'Team',
    status: 'todo',
    section: 'p6c',
    note: 'Team mechanics: two-lane shields, pressure plates, bosses that split across lanes. One raid boss rotates weekly. Quick wave 10 Matriarch already uses the two-lane shield (SL-04). Full wave 10 does not.',
  },
  {
    id: 'p6c-gear',
    title: 'Team set gear',
    owner: 'Team',
    status: 'todo',
    section: 'p6c',
    note: 'Gear slots, Common-to-S rarity, effects on towers and skills. Set bonuses when teammates wear the same set. Earned by play.',
  },
  {
    id: 'p6c-tiers',
    title: 'Difficulty tiers',
    owner: 'Team',
    status: 'todo',
    section: 'p6c',
    note: 'Better gear unlocks harder tiers with better loot, so gear never makes co-op trivial.',
  },
  {
    id: 'p6c-afk',
    title: 'AFK camp',
    owner: 'Team',
    status: 'todo',
    section: 'p6c',
    note: 'Resources build up per hour while away, capped at 12 hours, calculated on the server.',
  },
  {
    id: 'p6d-weekly',
    title: 'Weekly seeded challenge',
    owner: 'Team',
    status: 'todo',
    section: 'p6d',
    note: 'Everyone plays the same seed. The server re-runs the replay to verify the score.',
  },
  {
    id: 'p6d-boards',
    title: 'Leaderboards',
    owner: 'Team',
    status: 'todo',
    section: 'p6d',
    note: 'Regional and world boards, separate for players and for clans.',
  },
  {
    id: 'p6d-challenge',
    title: 'Clan challenges',
    owner: 'Team',
    status: 'todo',
    section: 'p6d',
    note: 'Beat our score within 24 hours. No queue.',
  },
  {
    id: 'p6d-wars',
    title: 'Weekend clan wars',
    owner: 'Team',
    status: 'todo',
    section: 'p6d',
    note: 'Scheduled windows so the clan is online at the same time.',
  },
  {
    id: 'g2-launch',
    title: 'CrazyGames Basic Launch',
    owner: 'Han',
    status: 'todo',
    section: 'gate2',
    note: 'No monetisation yet. Real players, real data. Same launch as D-05.',
  },
  {
    id: 'g2-gate',
    title: 'Gate: strangers come back',
    owner: 'Han',
    status: 'todo',
    section: 'gate2',
    note: 'About 25–30% back the next day and 7–8% after a week, plus playtime and repeat visits against the Reddit channels.',
  },
  {
    id: 'p7-cosmetics',
    title: 'Cosmetics shop',
    owner: 'Team',
    status: 'todo',
    section: 'p7',
    note: 'Hero and tower skins, clan banners, leaderboard frames.',
  },
  {
    id: 'p7-pass',
    title: 'Season pass',
    owner: 'Team',
    status: 'todo',
    section: 'p7',
    note: 'Cosmetic and convenience rewards along a seasonal track.',
  },
  {
    id: 'p7-forge',
    title: 'Forge spins',
    owner: 'Team',
    status: 'todo',
    section: 'p7',
    note: 'Odds shown, a pity guarantee, duplicates turned into shards, no trading. Region rules apply.',
  },
  {
    id: 'p7-sdk',
    title: 'CrazyGames purchases',
    owner: 'Han',
    status: 'todo',
    section: 'p7',
    note: 'Full launch with purchases. Optional rewarded ads in solo only.',
  },
  {
    id: 'p7-gate',
    title: 'Gate: first steady income',
    owner: 'Han',
    status: 'todo',
    section: 'p7',
    note: 'Even $100 a month shows that people pay. Then grow toward $2k.',
  },
  {
    id: 'p8-sends',
    title: 'Live 3v3 tower defense',
    owner: 'Team',
    status: 'todo',
    section: 'p8',
    note: 'Each side defends its own map and sends creeps. Bots fill empty seats. Gear is equalised.',
  },
  {
    id: 'p8-gate',
    title: 'Gate: short queues at peak',
    owner: 'Han',
    status: 'todo',
    section: 'p8',
    note: 'For example under 2 minutes in your region at peak hours.',
  },
  {
    id: 'p8-netcode',
    title: 'Netcode for hero fights',
    owner: 'Team',
    status: 'todo',
    section: 'p8',
    note: 'Faster response for your own hero, and servers in more regions.',
  },
  {
    id: 'p8-brawl',
    title: 'Paid 3v3 hero brawl',
    owner: 'Team',
    status: 'todo',
    section: 'p8',
    note: 'Brawl Pass: monthly, gear equalised, bots fill seats, scheduled hours, one free trial match.',
  },
  {
    id: 'p9-steam',
    title: 'Steam page and wishlists',
    owner: 'Han',
    status: 'todo',
    section: 'p9',
    note: 'Start months before a Steam release.',
  },
  {
    id: 'p9-stores',
    title: 'App Store and Google Play',
    owner: 'Both',
    status: 'todo',
    section: 'p9',
    note: 'Wrap the same web build with Capacitor, same protocol. Needs Apple and Google developer accounts.',
  },
  {
    id: 'p5-surges',
    title: 'Lane surges and match modifiers',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Protocol 15. From wave 6 some waves pile onto one lane, announced a wave ahead by a lane toast. The lobby and the match show one chip per modifier. The host can reroll until the match starts, or choose none. Solo surges are milder.',
    proof: pr(39),
  },
  {
    id: 'p5-rest',
    title: 'More maps',
    owner: 'Team',
    status: 'todo',
    section: 'backlog',
    note: 'The rest of Phase 5. Lane surges, match modifiers, and tower branches (tier 4) are already shipped. See docs/REPLAYABILITY.md.',
  },
  {
    id: 'p5-quick',
    title: 'Quick as the phone default?',
    owner: 'Han',
    status: 'todo',
    section: 'backlog',
    note: 'Han decides. See docs/MOBILE.md §11.',
  },
];

export const PROGRESS: ProgressData = {
  asOf: '2 Oct 2026',
  protocol: 17,
  polishLabel: 'T-00–T-06',
  polishComplete: true,
  nextGate: 'Gate 2',
  nextGateDetail: 'Public soft launch',
  phases: [
    { id: '1', title: 'Solo', state: 'done' },
    { id: '2', title: 'Online', state: 'done' },
    { id: '3', title: 'Content', state: 'done' },
    { id: '4a', title: 'Mobile', state: 'done' },
    { id: '4b', title: 'Polish', state: 'done' },
    { id: '5', title: 'Replayability', state: 'partial' },
    { id: '6', title: 'Live game', state: 'later' },
    { id: '7', title: 'Monetisation', state: 'later' },
    { id: '8', title: 'Live PvP', state: 'later' },
    { id: '9', title: 'Reach', state: 'later' },
  ],
  sections,
  items,
};
