/**
 * Structured status for the `/?progress` page.
 *
 * TASKS.md is the human tracker and stays the authority. This file is what the
 * dashboard reads. When a pull request finishes a task, update both TASKS.md and
 * this file in that same PR. How: docs/PROGRESS.md.
 *
 * Seeded from main as of 1 Oct 2026. Production protocol is 14.
 * Do not start Phase 6 from this page; it only reports status.
 */

import type { ProgressData, ProgressItem, ProgressProof, ProgressSection } from './model';

const REPO = 'https://github.com/Han1989/tgt-td-cld';

function pr(n: number): ProgressProof {
  return { label: `PR #${n}`, href: `${REPO}/pull/${n}` };
}

const sections: ProgressSection[] = [
  {
    id: 'gate1',
    title: 'Gate 1 · Friends playtest',
    blurb: 'Next gate. Two or three friends, saved match reports, then a go/no-go. Phase 6 waits on this.',
    group: 'now',
  },
  {
    id: 'han',
    title: 'Han, in parallel',
    blurb: 'Only Han can do these: phones, friends, accounts, and the hook-test server. None of them block the team from reading the tracker.',
    group: 'now',
  },
  {
    id: 'discovery',
    title: 'Discovery and rollout',
    blurb: 'Strangers, not just friends. Measurement is in. Posts and the go/no-go are Han.',
    group: 'now',
  },
  {
    id: 'polish',
    title: 'Polish · T-00–T-06',
    blurb: 'The polish path is done. CI, Hard, pings, the tutorial, projectile art, the docs, and co-op hook signals.',
    group: 'archive',
  },
  {
    id: 'earlier',
    title: 'Shipped earlier',
    blurb: 'The checklist’s “Done · 11 of 50”, already on main. The hook-test branch stays unmerged.',
    group: 'archive',
  },
  {
    id: 'p6a',
    title: 'Phase 6a · Accounts and data',
    blurb: 'Do not start before Gate 1 passes.',
    group: 'later',
  },
  {
    id: 'p6b',
    title: 'Phase 6b · Clans',
    blurb: 'Do not start before Gate 1 passes.',
    group: 'later',
  },
  {
    id: 'p6c',
    title: 'Phase 6c · Loot and progression',
    blurb: 'Do not start before Gate 1. Combos are rebuilt here; the hook-test branch is not merged.',
    group: 'later',
  },
  {
    id: 'p6d',
    title: 'Phase 6d · Competition',
    blurb: 'Do not start before Gate 1 passes.',
    group: 'later',
  },
  {
    id: 'gate2',
    title: 'Gate 2 · Public soft launch',
    blurb: 'After polish, with the Reddit posts. Same measurement bar as D-01 and D-06. Han calls the gate.',
    group: 'later',
  },
  {
    id: 'p7',
    title: 'Phase 7 · Monetisation',
    blurb: 'After Gate 2. No prices or odds without Han.',
    group: 'later',
  },
  {
    id: 'p8',
    title: 'Phase 8 · Live PvP',
    blurb: 'Last, after the co-op live game.',
    group: 'later',
  },
  {
    id: 'p9',
    title: 'Phase 9 · Reach',
    blurb: 'Only after Discovery shows strangers stay. Store-facing build leads with 1p and 2p; 3p stays the community flagship.',
    group: 'later',
  },
  {
    id: 'backlog',
    title: 'Backlog',
    blurb: 'Not scheduled. The rest of Phase 5, and one open decision.',
    group: 'later',
  },
];

const items: ProgressItem[] = [
  {
    id: 'g1-render',
    title: 'Render on Starter for the evening',
    owner: 'Han',
    status: 'todo',
    section: 'gate1',
    note: 'Switch both Render services to Starter for the playtest, then back to Free. Free sleeps and can drop matches.',
  },
  {
    id: 'g1-play',
    title: 'Play 2–3 matches with two friends',
    owner: 'Han',
    status: 'todo',
    section: 'gate1',
    note: 'Mix phones and desktop, and include the hook test. Everyone taps Save match report after each match.',
  },
  {
    id: 'g1-watch',
    title: 'Watch, don’t coach',
    owner: 'Han',
    status: 'todo',
    section: 'gate1',
    note: 'Note where people get confused, what makes them shout or laugh, and whether they use combos.',
  },
  {
    id: 'g1-tune',
    title: 'Per-hero tuning from the match reports',
    owner: 'Team',
    status: 'todo',
    section: 'gate1',
    note: 'After the matches. Use the saved reports (npm run replay), not bots alone. Quick pairs are the noisiest; Ranger + Warden is the weakest pair.',
  },
  {
    id: 'g1-gate',
    title: 'Gate: they ask to play again',
    owner: 'Han',
    status: 'todo',
    section: 'gate1',
    note: 'At least half the players ask to play again unprompted. If not, rework the hook before Phase 6.',
  },
  {
    id: 'H-01',
    title: 'Let friends open preview links',
    owner: 'Han',
    status: 'todo',
    section: 'han',
    note: 'Vercel → Settings → Deployment Protection → Vercel Authentication: Disabled. Otherwise friends see a login page.',
  },
  {
    id: 'H-02',
    title: 'Confirm the hook-test server',
    owner: 'Han',
    status: 'todo',
    section: 'han',
    note: 'In Render, check tgt-td-spike is Live and copy its address. /health should show shard H. On 30 Sep the public URL returned 404.',
  },
  {
    id: 'H-03',
    title: 'Try the hook test on a phone',
    owner: 'Han',
    status: 'todo',
    section: 'han',
    note: 'Solo with the bot ally first (?spike=hook&practice), then online with one friend against the spike server.',
  },
  {
    id: 'H-04',
    title: 'Three music tracks (optional)',
    owner: 'Han',
    status: 'todo',
    section: 'han',
    note: 'lobby.mp3, match.mp3, and boss.mp3. Licensed for a paid game. Upload through a PR; see docs/SOUND_FILES.md.',
  },
  {
    id: 'H-05',
    title: 'Test on an iPhone',
    owner: 'Han',
    status: 'todo',
    section: 'han',
    note: 'Safari has the most quirks. Run docs/MOBILE_TESTING.md once and fill in its Results table.',
  },
  {
    id: 'H-06',
    title: 'Give the team GitHub access',
    owner: 'Han',
    status: 'todo',
    section: 'han',
    note: 'Write access for branches and pull requests. Merging stays with Han.',
  },
  {
    id: 'D-01',
    title: 'Channel analytics',
    owner: 'Team',
    status: 'done',
    section: 'discovery',
    note: 'Playtime, D1/D7 retention, repeat visits, and a post-match rating, tagged by source. First-party HTTP on the game server. Not Phase 6a accounts.',
    proof: pr(25),
  },
  {
    id: 'SL-01',
    title: 'Soft-launch co-op presentation',
    owner: 'Team',
    status: 'done',
    section: 'discovery',
    note: 'Mirrored ping and emote burst, gift sent/received toasts, and a twin-ultimate ribbon from cast events. Sim signals (leak lane, gift totals, syncCast, boss hints) are protocol 14 (T-06). The live wires are SL-02.',
    proof: pr(35),
  },
  {
    id: 'SL-02',
    title: 'Soft-launch HUD hooks',
    owner: 'Team',
    status: 'done',
    section: 'discovery',
    note: 'Lane clutch names the leaking lane and skips the Hard finale strain. The end screen shows gold given and received. The twin ribbon prefers syncCast. Boss waves add advisory lane banners. Protocol stays 14.',
    proof: pr(36),
  },
  {
    id: 'D-02',
    title: 'Post to r/PlayMyGame',
    owner: 'Han',
    status: 'todo',
    section: 'discovery',
    note: 'Follow the sub’s rules. One clear link, with the channel tag.',
  },
  {
    id: 'D-03',
    title: 'Post to r/incremental_games',
    owner: 'Han',
    status: 'todo',
    section: 'discovery',
    note: 'Only if the pitch fits. Follow the sub’s rules and use the channel tag.',
  },
  {
    id: 'D-04',
    title: 'Post to r/cozygames',
    owner: 'Han',
    status: 'todo',
    section: 'discovery',
    note: 'Only if the pitch fits. Follow the sub’s rules and use the channel tag.',
  },
  {
    id: 'D-05',
    title: 'CrazyGames Basic Launch',
    owner: 'Han',
    status: 'todo',
    section: 'discovery',
    note: 'Same work as Gate 2 g2-launch. Before or alongside store submission, not instead of polish.',
  },
  {
    id: 'D-06',
    title: 'Review channels and call go or no-go',
    owner: 'Han',
    status: 'todo',
    section: 'discovery',
    note: 'Playtime, retention, and repeats per channel. Friends-only signal is not enough to push stores.',
  },
  {
    id: 'T-00',
    title: 'CI and branch protection',
    owner: 'Both',
    status: 'done',
    section: 'polish',
    note: 'GitHub Actions runs tests and the build on pull requests and main. main requires the ci check. Branch protection is on.',
    proof: pr(24),
  },
  {
    id: 'T-01',
    title: 'Hard difficulty and an expert bot',
    owner: 'Team',
    status: 'done',
    section: 'polish',
    note: 'Hard scales creep HP and counts. The casual bot stays the Normal 40–80 gate. The expert bot holds Hard at 40–80. Protocol 12.',
    proof: pr(28),
  },
  {
    id: 'T-02',
    title: 'Team pings and quick-chat',
    owner: 'Team',
    status: 'done',
    section: 'polish',
    note: 'Long-press or Alt-click pings the map. Six emotes, no free-text chat. Protocol 13.',
    proof: pr(29),
  },
  {
    id: 'T-03',
    title: 'First-match tutorial',
    owner: 'Team',
    status: 'done',
    section: 'polish',
    note: 'A new player’s first solo match is a skippable Quick lesson on Normal. Online rooms do not start it. Replay from Settings.',
    proof: pr(30),
  },
  {
    id: 'T-04',
    title: 'Projectile and trap art',
    owner: 'Team',
    status: 'done',
    section: 'polish',
    note: 'Every shot style and the Snare Trap are Runelight sprites. ?showcase lists them in Normal and Bright.',
    proof: pr(26),
  },
  {
    id: 'T-05',
    title: 'Docs clean-up',
    owner: 'Team',
    status: 'done',
    section: 'polish',
    note: 'README status, docs/ROADMAP.md, GAME_DESIGN §11 (Phases 6–8 after Gate 1), and AGENTS.md.',
    proof: pr(31),
  },
  {
    id: 'T-06',
    title: 'Soft-launch co-op hook signals',
    owner: 'Team',
    status: 'done',
    section: 'polish',
    note: 'Protocol 14. Leak events carry a lane. Reports count gold gifted and received. A syncCast marks overlapping ultimates, with no extra damage. Boss lane lines are advisory. Double-ping FX stays on the client.',
    proof: pr(34),
  },
  {
    id: 'a-units',
    title: 'Units art',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Heroes, creeps, and bosses drawn in Runelight.',
    proof: pr(16),
  },
  {
    id: 'a-branches',
    title: 'Old branches cleaned up',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Merged branches now delete themselves. A repository setting, not a pull request.',
  },
  {
    id: 'a-mana',
    title: 'Ultimates cost no mana',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Ultimates are cooldown only. Mana regen grows with level.',
    proof: { label: 'Decision log', href: `${REPO}/blob/main/docs/GAME_DESIGN.md` },
  },
  {
    id: 'a-mana-merge',
    title: 'Hero mana rework merged',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Free ultimates, level-scaled regen, and mana costs on the skill buttons.',
    proof: pr(17),
  },
  {
    id: 'a-cap3',
    title: 'Matches locked to 3 players',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'One player per lane. The 4-player setup is gone.',
    proof: pr(18),
  },
  {
    id: 'a-feel',
    title: 'Mobile feel pass',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Your hero draws its walk at once, solo renders 40 ms behind, and the Warden’s swing reads on a phone.',
    proof: pr(19),
  },
  {
    id: 'a-reach',
    title: 'Melee reach fix',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'A hero reaches a creep from attack range plus both radii. An idle melee hero steps in and fights.',
    proof: pr(20),
  },
  {
    id: 'a-fix1',
    title: 'Playtest round 1 fixes',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Match reports and replays, the team difficulty curve, and mana that lasts about twice as long.',
    proof: pr(21),
  },
  {
    id: 'a-sound',
    title: 'Sound pass',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Music and effects made in code with the Web Audio API. No sound files.',
    proof: pr(22),
  },
  {
    id: 'a-theme',
    title: 'Sound theme',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Japanese garden in the lobby, Three Kingdoms battles in a match. No recorded files yet.',
    proof: pr(23),
  },
  {
    id: 'b-spike',
    title: 'Hook test (never merge)',
    owner: 'Team',
    status: 'done',
    section: 'earlier',
    note: 'Combo ultimates, a boss shield, and a solo bot ally, behind ?spike=hook. The branch stays unmerged. Combos are rebuilt in Phase 6c.',
    proof: { label: 'Branch (do not merge)', href: `${REPO}/tree/claude/loving-hawking-7fvsu7` },
  },
  {
    id: 'p6a-db',
    title: 'Choose the database host',
    owner: 'Han',
    status: 'todo',
    section: 'p6a',
    note: 'Render Postgres, or AWS. Han decides.',
  },
  {
    id: 'p6a-accounts',
    title: 'Accounts and saved progress',
    owner: 'Team',
    status: 'todo',
    section: 'p6a',
    note: 'Play as a guest first. Link Google, Apple, or email later. Currencies and inventory live on the server.',
  },
  {
    id: 'p6a-analytics',
    title: 'Analytics and crash reports',
    owner: 'Team',
    status: 'todo',
    section: 'p6a',
    note: 'Day-1, day-7, and day-30 return rates, match results, and where new players quit. D-01 is the smaller funnel until then.',
  },
  {
    id: 'p6a-privacy',
    title: 'Privacy basics',
    owner: 'Team',
    status: 'todo',
    section: 'p6a',
    note: 'Privacy policy, data export and deletion, and an age check.',
  },
  {
    id: 'p6b-clans',
    title: 'Clans of 3',
    owner: 'Team',
    status: 'todo',
    section: 'p6b',
    note: 'Create, invite by link, join, and leave. Clan level and banner.',
  },
  {
    id: 'p6b-party',
    title: 'Play as a clan',
    owner: 'Team',
    status: 'todo',
    section: 'p6b',
    note: 'Party up and queue together. Quick-chat only.',
  },
  {
    id: 'p6c-combos',
    title: 'Combo ultimates',
    owner: 'Team',
    status: 'todo',
    section: 'p6c',
    note: 'A fused effect for every hero pair. Rebuild the hook test properly. Do not merge claude/loving-hawking-7fvsu7.',
  },
  {
    id: 'p6c-raids',
    title: 'Raid bosses',
    owner: 'Team',
    status: 'todo',
    section: 'p6c',
    note: 'Team mechanics: two-lane shields, pressure plates, bosses that split across lanes. One raid boss rotates weekly.',
  },
  {
    id: 'p6c-gear',
    title: 'Team set gear',
    owner: 'Team',
    status: 'todo',
    section: 'p6c',
    note: 'Gear slots, Common-to-S rarity, effects on towers and skills. Set bonuses when teammates wear the same set. Earned by play.',
  },
  {
    id: 'p6c-tiers',
    title: 'Difficulty tiers',
    owner: 'Team',
    status: 'todo',
    section: 'p6c',
    note: 'Better gear unlocks harder tiers with better loot, so gear never makes co-op trivial.',
  },
  {
    id: 'p6c-afk',
    title: 'AFK camp',
    owner: 'Team',
    status: 'todo',
    section: 'p6c',
    note: 'Resources build up per hour while away, capped at 12 hours, calculated on the server.',
  },
  {
    id: 'p6d-weekly',
    title: 'Weekly seeded challenge',
    owner: 'Team',
    status: 'todo',
    section: 'p6d',
    note: 'Everyone plays the same seed. The server re-runs the replay to verify the score.',
  },
  {
    id: 'p6d-boards',
    title: 'Leaderboards',
    owner: 'Team',
    status: 'todo',
    section: 'p6d',
    note: 'Regional and world boards, separate for players and for clans.',
  },
  {
    id: 'p6d-challenge',
    title: 'Clan challenges',
    owner: 'Team',
    status: 'todo',
    section: 'p6d',
    note: 'Beat our score within 24 hours. No queue.',
  },
  {
    id: 'p6d-wars',
    title: 'Weekend clan wars',
    owner: 'Team',
    status: 'todo',
    section: 'p6d',
    note: 'Scheduled windows so the clan is online at the same time.',
  },
  {
    id: 'g2-launch',
    title: 'CrazyGames Basic Launch',
    owner: 'Han',
    status: 'todo',
    section: 'gate2',
    note: 'No monetisation yet. Real players, real data. Same launch as D-05.',
  },
  {
    id: 'g2-gate',
    title: 'Gate: strangers come back',
    owner: 'Han',
    status: 'todo',
    section: 'gate2',
    note: 'About 25–30% back the next day and 7–8% after a week, plus playtime and repeat visits against the Reddit channels.',
  },
  {
    id: 'p7-cosmetics',
    title: 'Cosmetics shop',
    owner: 'Team',
    status: 'todo',
    section: 'p7',
    note: 'Hero and tower skins, clan banners, leaderboard frames.',
  },
  {
    id: 'p7-pass',
    title: 'Season pass',
    owner: 'Team',
    status: 'todo',
    section: 'p7',
    note: 'Cosmetic and convenience rewards along a seasonal track.',
  },
  {
    id: 'p7-forge',
    title: 'Forge spins',
    owner: 'Team',
    status: 'todo',
    section: 'p7',
    note: 'Odds shown, a pity guarantee, duplicates turned into shards, no trading. Region rules apply.',
  },
  {
    id: 'p7-sdk',
    title: 'CrazyGames purchases',
    owner: 'Han',
    status: 'todo',
    section: 'p7',
    note: 'Full launch with purchases. Optional rewarded ads in solo only.',
  },
  {
    id: 'p7-gate',
    title: 'Gate: first steady income',
    owner: 'Han',
    status: 'todo',
    section: 'p7',
    note: 'Even $100 a month shows that people pay. Then grow toward $2k.',
  },
  {
    id: 'p8-sends',
    title: 'Live 3v3 tower defense',
    owner: 'Team',
    status: 'todo',
    section: 'p8',
    note: 'Each side defends its own map and sends creeps. Bots fill empty seats. Gear is equalised.',
  },
  {
    id: 'p8-gate',
    title: 'Gate: short queues at peak',
    owner: 'Han',
    status: 'todo',
    section: 'p8',
    note: 'For example under 2 minutes in your region at peak hours.',
  },
  {
    id: 'p8-netcode',
    title: 'Netcode for hero fights',
    owner: 'Team',
    status: 'todo',
    section: 'p8',
    note: 'Faster response for your own hero, and servers in more regions.',
  },
  {
    id: 'p8-brawl',
    title: 'Paid 3v3 hero brawl',
    owner: 'Team',
    status: 'todo',
    section: 'p8',
    note: 'Brawl Pass: monthly, gear equalised, bots fill seats, scheduled hours, one free trial match.',
  },
  {
    id: 'p9-steam',
    title: 'Steam page and wishlists',
    owner: 'Han',
    status: 'todo',
    section: 'p9',
    note: 'Start months before a Steam release.',
  },
  {
    id: 'p9-stores',
    title: 'App Store and Google Play',
    owner: 'Both',
    status: 'todo',
    section: 'p9',
    note: 'Wrap the same web build with Capacitor, same protocol. Needs Apple and Google developer accounts.',
  },
  {
    id: 'p5-rest',
    title: 'Rest of Phase 5',
    owner: 'Team',
    status: 'todo',
    section: 'backlog',
    note: 'Lane surges, match modifiers, and more maps. Tower branches (tier 4) are already shipped. See docs/REPLAYABILITY.md.',
  },
  {
    id: 'p5-quick',
    title: 'Quick as the phone default?',
    owner: 'Han',
    status: 'todo',
    section: 'backlog',
    note: 'Han decides. See docs/MOBILE.md §11.',
  },
];

export const PROGRESS: ProgressData = {
  asOf: '1 Oct 2026',
  protocol: 14,
  polishLabel: 'T-00–T-06',
  polishComplete: true,
  nextGate: 'Gate 1',
  nextGateDetail: 'Friends playtest',
  phases: [
    { id: '1', title: 'Solo', state: 'done' },
    { id: '2', title: 'Online', state: 'done' },
    { id: '3', title: 'Content', state: 'done' },
    { id: '4a', title: 'Mobile', state: 'done' },
    { id: '4b', title: 'Polish', state: 'done' },
    { id: '5', title: 'Replayability', state: 'partial' },
    { id: '6', title: 'Live game', state: 'later' },
    { id: '7', title: 'Monetisation', state: 'later' },
    { id: '8', title: 'Live PvP', state: 'later' },
    { id: '9', title: 'Reach', state: 'later' },
  ],
  sections,
  items,
};
