// The service worker's source (docs/MOBILE.md §7), generated by vite.config.ts at build time; a pure
// function so a unit test can run it against fake caches.
//
// - The app shell (index.html, the hashed JS / CSS / worker chunks and the public files) is precached
//   on install, so the app starts fast and solo plays offline. The cache name is a hash of the file
//   list, so every deploy installs a new worker, which waits until the page asks it to take over
//   ("Update available — tap to reload").
// - Recorded sound files (`/music/*.mp3`, `/sfx/*.mp3`, docs/SOUND_FILES.md) are never precached:
//   music is several MB, and a player who never hears the boss music shouldn't download it on install.
//   Each one is cached the first time the game fetches it, in a cache that outlives deploys
//   (`tdt-media`); the URL carries the file's hash (`?v=`), so a new upload is fetched fresh and
//   replaces the old copy.
// - It only serves same-origin GET requests; the game server's WebSocket never goes through it.

/** Files in the shell that are not precached: recorded sound files (cached on first play instead). */
export function isMediaPath(path: string): boolean {
  return /^\/(music|sfx)\//.test(path);
}

export const MEDIA_CACHE = 'tdt-media';

export function swSource(version: string, files: string[]): string {
  const shell = files.filter((f) => !isMediaPath(f));
  return `// Generated by vite.config.ts at build time. Do not edit.
const CACHE = 'tdt-${version}';
const MEDIA = '${MEDIA_CACHE}';
const SHELL = ${JSON.stringify(shell)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(SHELL)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('tdt-') && k !== CACHE && k !== MEDIA).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// The page asks a waiting worker to take over when the player taps "Update available".
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

// A recorded sound file: from the media cache, else the network, kept for next time (older uploads
// of the same file are dropped).
function media(req, url) {
  return caches.open(MEDIA).then((cache) =>
    cache.match(req).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res.ok && res.status === 200) {
          const copy = res.clone();
          cache
            .keys()
            .then((keys) => Promise.all(keys.filter((k) => new URL(k.url).pathname === url.pathname && k.url !== req.url).map((k) => cache.delete(k))))
            .then(() => cache.put(req, copy))
            .catch(() => {});
        }
        return res;
      });
    }),
  );
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Only this site's own files; never the game server.
  if (url.origin !== self.location.origin || url.pathname === '/sw.js') return;
  if (/^\\/(music|sfx)\\//.test(url.pathname)) {
    event.respondWith(media(req, url));
    return;
  }
  if (req.mode === 'navigate') {
    // App shell first (fast start, offline solo); the network if it is not cached yet.
    event.respondWith(caches.match('/index.html').then((hit) => hit || fetch(req)));
    return;
  }
  event.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req)));
});
`;
}
